# Generated by Django 4.2.6 on 2023-12-01 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=20, verbose_name='CountryCode')),
            ],
            options={
                'verbose_name': 'CountryCode',
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=35, verbose_name='Language')),
                ('IsOfficial', models.CharField(choices=[('T', 'F')], max_length=20)),
                ('Percentage', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Pecentage')),
                ('Family', models.CharField(max_length=30, verbose_name='Family')),
                ('Dialect', models.CharField(max_length=30, verbose_name='Dialect')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='CountryLanguages')),
                ('CountryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Country.country')),
            ],
            options={
                'verbose_name': 'CountryLanguages',
                'verbose_name_plural': 'CountryLanguages',
            },
        ),
    ]
