# Generated by Django 4.2.6 on 2023-12-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code')),
                ('Name', models.CharField(max_length=52, verbose_name='Name')),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('Africa', 'Africa'), ('Antartica', 'Antartica'), ('Oceania', 'Oceania'), ('North America', 'North America'), ('South America', 'South America')], max_length=20)),
                ('Region', models.CharField(max_length=26, verbose_name='Region')),
                ('SurfaceArea', models.DecimalField(decimal_places=2, max_digits=10.2, verbose_name='SurfaceArea')),
                ('IndepYear', models.SmallIntegerField(max_length=10, verbose_name='IndepYear')),
                ('Population', models.IntegerField(max_length=20, verbose_name='Population')),
                ('LifeExpentacy', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='LifeExpentacy')),
                ('GNP', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GNP')),
                ('GNPOld', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='GNPOld')),
                ('LocalName', models.CharField(max_length=45, verbose_name='LocalName')),
                ('GovermentForm', models.CharField(max_length=45, verbose_name='GovermentForm')),
                ('HeadOfState', models.CharField(max_length=60, verbose_name='HeadOfState')),
                ('Capital', models.IntegerField(max_length=5, verbose_name='Capital')),
                ('Code2', models.CharField(max_length=2, verbose_name='Code2')),
                ('Money', models.CharField(max_length=30, verbose_name='Money')),
                ('IDH', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IDH')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes Country',
                'ordering': ['Name'],
                'unique_together': {('Code', 'Name')},
            },
        ),
    ]
